services:
  ### Vector model server (Ollama)
  ollama:
    build:
      context: ./ollama-service
      dockerfile: Dockerfile
    image: rnd_ollama:latest
    container_name: rnd_ollama
    ports:
      - "11435:11434"
    volumes:
      - ./ollama-service/Modelfile/Modelfile:/root/.ollama/Modelfile
      - ./ollama-service/models:/root/.ollama/models
    environment:
      - OLLAMA_HOST=0.0.0.0

  ### Jupyter Notebook environment
  rnd-chat-dev:
    build:
      context: ./chat-dev
      dockerfile: Dockerfile
    image: rnd-chat-dev:latest
    container_name: rnd-chat-dev
    # network_mode: "host" 제거 - 브리지 네트워크 사용
    ports:
      - "8888:8888"
    volumes:
      - ./chat-dev:/home/jovyan/work
      - ./ollama-service/models:/home/jovyan/work/models
      - ./vector_db:/home/jovyan/work/vector_db
    shm_size: "512m"
    environment:
      - JUPYTER_TOKEN=devtoken
      - OLLAMA_BASE_URL=http://ollama:11434  # 컨테이너 이름으로 접근
    depends_on:
      - ollama
    dns:
        # Google Public DNS 서버
      - 8.8.8.8
      - 8.8.4.4
      # Cloudflare Public DNS 서버
      - 1.1.1.1
      - 1.0.0.1 