services:
  ### Vector model server (Ollama)
  ollama:
    build:
      context: ./ollama-service
      dockerfile: Dockerfile
    image: rnd_ollama:latest
    container_name: rnd_ollama
    ports:
      - "11435:11434"
    volumes:
      - ./ollama-service/Modelfile/Modelfile:/root/.ollama/Modelfile
      - ./ollama-service/models:/root/.ollama/models
      
    environment:
      - OLLAMA_HOST=0.0.0.0


  ### Vector store (Qdrant)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rnd_qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./vector_db:/qdrant/storage


  ### Jupyter Notebook environment
  rnd-chat-dev:
    build:
      context: ./chat-dev
      dockerfile: Dockerfile
    image: rnd-chat-dev:latest
    container_name: rnd-chat-dev
    ports:
      - "8888:8888"
    volumes:
      - ./chat-dev:/home/jovyan/work
      - ./ollama-service/models:/home/jovyan/work/models
      - ./vector_db:/home/jovyan/work/vector_db
    shm_size: "512m"
    environment:
      - JUPYTER_TOKEN=devtoken
      - OLLAMA_BASE_URL=http://ollama:11434
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - ollama
      - qdrant

  