FROM qdrant/qdrant:latest
# curl 설치 (헬스체크용)
# RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

USER root

RUN set -eux; \
    rm -rf /var/lib/apt/lists/*; \
    apt-get update -o Acquire::Retries=5 -o Acquire::http::Timeout=30 -o Acquire::ForceIPv4=true; \
    apt-get install -y --no-install-recommends ca-certificates curl; \
    update-ca-certificates; \
    rm -rf /var/lib/apt/lists/*

USER 1000