FROM ollama/ollama:0.11.5-rc3

COPY ./app/ollama_data/Modelfile/ /root/.ollama/Modelfile/

# 시작 스크립트 복사
COPY ./app/start.sh /start.sh
RUN chmod +x /start.sh

# 모델 준비 상태 헬스체크
HEALTHCHECK CMD ollama list | grep -q "ko-llama-8B" || exit 1

# 시작 스크립트 실행
ENTRYPOINT ["/start.sh"]