version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./vector_data/storage:/qdrant/storage
      - ./vector_data/backup:/qdrant/snapshots
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6333/readyz"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./
      dockerfile: rag_chatbot/Dockerfile.cpu
    container_name: rag-backend
    env_file:
      - ./rag_chatbot/backend/.env.dev
    environment:
      - QDRANT_URL=http://qdrant:6333
      - DATA_DIR=/app/rag_chatbot/data
      - EMBEDDING_MODEL_NAME=/app/rag_chatbot/embedding_models/BGE-m3-ko
    volumes:
      - ./rag_chatbot/embedding_models:/app/rag_chatbot/embedding_models:ro
      - ./rag_chatbot/data:/app/rag_chatbot/data:ro
    ports:
      - "8000:8000"
    depends_on:
      qdrant:
        condition: service_healthy

