version: "3.8"
services:
  rnd-chat-dev:
    build:
      context: ./rnd-chat-dev
      dockerfile: Dockerfile
    image: rnd-chat-dev:latest
    container_name: rnd-chat-dev
    ports:
      - "8888:8888"
    volumes:
      - ./rnd-chat-dev:/workspace
    environment:
      - JUPYTER_TOKEN=localdev
      - NVIDIA_VISIBLE_DEVICES=3
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    shm_size: "1g"
    cpus: '8'
    mem_limit: 8G
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: [gpu]